require('dotenv').config()
const express = require('express')
const mongoose = require('mongoose')
const shoeRoute = require('./routes/shoe')
const adminRoute = require('./routes/admin')
const userRoute = require('./routes/user')
const cartRoute = require('./routes/cart')
const addressRoute = require('./routes/address')
const checkoutRoute = require('./routes/checkout')
const deliveryMethodRoute = require('./routes/deliveryMethod')
const paymentRoute = require('./routes/payment')
const cors = require('cors')
const bodyParser = require('body-parser')
const app = express()

app.use(cors())
app.use(express.json())
app.use(bodyParser.json())

app.use('/uploads', express.static('uploads'))

app.use('/api/admin', adminRoute)
app.use('/api/user', userRoute)
app.use('/api/shoe', shoeRoute)
app.use('/api/cart', cartRoute)
app.use('/api/address', addressRoute)
app.use('/api/checkout', checkoutRoute)
app.use('/api/delivery', deliveryMethodRoute)
app.use('/api/payment', paymentRoute)

mongoose.connect(process.env.DB_URL)
    .then(() => {
        app.listen(process.env.PORT, () => console.log('connected to db & listening on port', process.env.PORT))
    })
    .catch((error) => console.log(error))

