const ShoeData = [
    {
        id_sepatu: 1,
        gambar1: '/shoes/converse1.png',
        gambar2: '/shoes/converse2.png',
        gambar3: '/shoes/converse3.png',
        brand: 'Converse',
        model: 'CDG Multi Hearts High',
        warna: 'Putih',
        size: 44,
        stok: 1,
        harga: '1.300.0000',
        potongan: 0,
    },
    {
        id_sepatu: 2,
        gambar1: '/shoes/vans1.png',
        gambar2: '/shoes/vans2.png',
        gambar3: '/shoes/vans3.png',
        brand: 'Vans',
        model: 'SK8 HI',
        warna: 'Merah',
        size: 43,
        stok: 1,
        harga: '450.0000',
        potongan: 0,
    },
    {
        id_sepatu: 3,
        gambar1: '/shoes/nike1.png',
        gambar2: '/shoes/nike2.png',
        gambar3: '/shoes/nike3.png',
        brand: 'Nike',
        model: 'Air Max 90',
        warna: 'Abu',
        size: 44,
        stok: 1,
        harga: '420.000',
        potongan: 0,
    },
];

export default ShoeData